# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: release

on:
    push:
        tags:
            - "**"

jobs:
    release-windows:
        runs-on: windows-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "stable"

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "multi-proxy-downloader-win.exe"

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: multi-proxy-downloader-win.exe

    release-linux:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "stable"

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "multi-proxy-downloader-linux"

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: multi-proxy-downloader-linux

    release-macos:
        runs-on: macos-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "stable"

            - name: Build
              run: |
                  go mod tidy
                  go build -ldflags "-w -s" -o "multi-proxy-downloader-macos"

            - name: GH Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  body_path: .github/release-notes.md
                  files: multi-proxy-downloader-macos
